title: Liu Peijie's Homepage
page-top-title: Liu Peijie
top-section-bg-text: Be what you wanna be
home-subtitle: Liu Peijie&ensp;|&ensp;不骄不躁の杰
copyright-text: '&copy; Liu Peijie 2023-2026. All Rights Reserved. Last Updated: Jan 2026.'
